/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Chefu
 */
public class pClientes extends javax.swing.JPanel {

    /**
     * Creates new form pClientes
     */
    public pClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tDireccionC = new javax.swing.JTextField();
        lProveedores = new javax.swing.JLabel();
        bAgregarC = new javax.swing.JButton();
        eNitC = new javax.swing.JLabel();
        bEliminarC = new javax.swing.JButton();
        eNombreC = new javax.swing.JLabel();
        bBuscarC = new javax.swing.JButton();
        eDireccionC = new javax.swing.JLabel();
        bModificarC = new javax.swing.JButton();
        bReporteC = new javax.swing.JButton();
        bBinarioC = new javax.swing.JButton();
        tNitC = new javax.swing.JTextField();
        tNombreC = new javax.swing.JTextField();

        lProveedores.setText("Clientes");

        bAgregarC.setText("Agregar");

        eNitC.setText("Nit de Cliente:");

        bEliminarC.setText("Eliminar");

        eNombreC.setText("Nombre de Cliente:");

        bBuscarC.setText("Buscar");

        eDireccionC.setText("Direccion de Cliente:");

        bModificarC.setText("Modificar");

        bReporteC.setText("Reporte");

        bBinarioC.setText("Binario");

        tNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eNitC)
                            .addComponent(eNombreC)
                            .addComponent(eDireccionC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tDireccionC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(tNombreC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNitC)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(bModificarC))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bAgregarC, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bReporteC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bEliminarC, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bBinarioC)
                            .addComponent(bBuscarC))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lProveedores)
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNitC)
                    .addComponent(tNitC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNombreC)
                    .addComponent(tNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eDireccionC)
                    .addComponent(tDireccionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregarC)
                    .addComponent(bEliminarC)
                    .addComponent(bBuscarC))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bModificarC)
                    .addComponent(bReporteC)
                    .addComponent(bBinarioC))
                .addContainerGap(268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarC;
    private javax.swing.JButton bBinarioC;
    private javax.swing.JButton bBuscarC;
    private javax.swing.JButton bEliminarC;
    private javax.swing.JButton bModificarC;
    private javax.swing.JButton bReporteC;
    private javax.swing.JLabel eDireccionC;
    private javax.swing.JLabel eNitC;
    private javax.swing.JLabel eNombreC;
    private javax.swing.JLabel lProveedores;
    private javax.swing.JTextField tDireccionC;
    private javax.swing.JTextField tNitC;
    private javax.swing.JTextField tNombreC;
    // End of variables declaration//GEN-END:variables
}
