/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import Clases.cArticulo;
import Clases.cCliente;
import Clases.cEmpleado;
import Clases.cFactura;
import Clases.cVentaArticulo;
import Principal.Main;
import java.awt.BorderLayout;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chefu
 */
public class pFacturas extends javax.swing.JPanel {

    /**
     * Creates new form pFacturas
     */
    ArrayList<cVentaArticulo> ArregloVA = new ArrayList<cVentaArticulo>();

    public static ArrayList<cFactura> getArregloFac() {
        return ArregloFac;
    }
    private static ArrayList<cFactura> ArregloFac = new ArrayList<cFactura>();
    cCliente ClienteSel = null;
    cEmpleado EmpleadoSel = null;

    public pFacturas() {
        pClientes.leerBinario();
        pEmpleados.leerbinario();
        pArticulos.leerBinarioAr();
        initComponents();
        leerbinario();
        correlativo();
        setearCB();
        setearCBE();
        setearCBCA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelClientes = new javax.swing.JPanel();
        bAgregarCl = new javax.swing.JButton();
        cbClientes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbEmpleados = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tPuestoE = new javax.swing.JTextField();
        cbCajas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lCodigoA = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lDescripcionA = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lPrecioUnitA = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lCantidadA = new javax.swing.JList<>();
        cbCArticulos = new javax.swing.JComboBox<>();
        bAgregarArt = new javax.swing.JButton();
        cbCantArticulos = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lSubtotalA = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tIVA = new javax.swing.JTextField();
        tPago = new javax.swing.JTextField();
        lCambio = new javax.swing.JLabel();
        lCCambio = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bRVenta = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lCorrelativo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lNombre = new javax.swing.JList<>();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Factura");

        PanelClientes.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelClientesLayout = new javax.swing.GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelClientesLayout.setVerticalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        bAgregarCl.setText("Agregar Cliente");
        bAgregarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarClActionPerformed(evt);
            }
        });

        cbClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClientesItemStateChanged(evt);
            }
        });

        jLabel2.setText("Empleado:");

        cbEmpleados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEmpleadosItemStateChanged(evt);
            }
        });

        jLabel3.setText("No. Caja:");

        jLabel4.setText("Puesto:");

        tPuestoE.setEditable(false);

        cbCajas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caja 1", "Caja 2", "Caja 3", "Caja 4", "Caja 5" }));

        jScrollPane1.setViewportView(lCodigoA);

        jScrollPane2.setViewportView(lDescripcionA);

        jScrollPane3.setViewportView(lPrecioUnitA);

        jScrollPane4.setViewportView(lCantidadA);

        cbCArticulos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCArticulosItemStateChanged(evt);
            }
        });

        bAgregarArt.setText("Agregar Articulo");
        bAgregarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarArtActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar Articulo");

        jScrollPane5.setViewportView(lSubtotalA);

        jLabel5.setText("Cod.");

        jLabel6.setText("Descripcion.");

        jLabel7.setText("Precio U.");

        jLabel8.setText("Cantidad.");

        jLabel9.setText("Subtotal.");

        tTotal.setEditable(false);
        tTotal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tTotalPropertyChange(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Total:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("IVA:");

        tIVA.setEditable(false);

        tPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tPagoKeyReleased(evt);
            }
        });

        lCambio.setText("Cambio:");

        lCCambio.setText("00.00");

        jLabel12.setText("Pago:");

        bRVenta.setText("Realizar Venta");
        bRVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRVentaActionPerformed(evt);
            }
        });

        jLabel13.setText("No. Correlativo");

        lCorrelativo.setText("------");

        jLabel14.setText("Nombre");

        jScrollPane6.setViewportView(lNombre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lCambio)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lCCambio)
                                                .addGap(77, 77, 77)
                                                .addComponent(bRVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(4, 4, 4)
                                                        .addComponent(tPago, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel14))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel6)
                                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                                    .addComponent(tIVA)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel8)
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9))
                                                .addGap(0, 0, 0))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bAgregarCl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 34, Short.MAX_VALUE))
                            .addComponent(PanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCajas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tPuestoE, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCantArticulos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bAgregarArt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13)
                    .addComponent(lCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregarCl)
                    .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(PanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(tPuestoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbCArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAgregarArt)
                    .addComponent(jButton2)
                    .addComponent(cbCantArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(tPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lCCambio)
                        .addComponent(bRVenta))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarClActionPerformed
        // TODO add your handling code here:
        addpanel(new pClientes());
    }//GEN-LAST:event_bAgregarClActionPerformed

    private void cbClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClientesItemStateChanged
        // TODO add your handling code here:
        if (BuscarCliente(cbClientes.getSelectedItem().toString())) {
            addpanel(new pViewClientes(ClienteSel));
        } else {
            PanelClientes.removeAll();
            PanelClientes.revalidate();
            PanelClientes.repaint();
        }
    }//GEN-LAST:event_cbClientesItemStateChanged

    private void cbEmpleadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEmpleadosItemStateChanged
        // TODO add your handling code here:
        if (BuscarEmpleado(cbEmpleados.getSelectedItem().toString())) {
            tPuestoE.setText(EmpleadoSel.getPuestoEmpleado());
        } else {
            tPuestoE.setText("");
        }
    }//GEN-LAST:event_cbEmpleadosItemStateChanged

    private void cbCArticulosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCArticulosItemStateChanged
        // TODO add your handling code here:
        setearCantBCA(cbCArticulos.getSelectedItem().toString());
    }//GEN-LAST:event_cbCArticulosItemStateChanged

    private void bAgregarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarArtActionPerformed
        // TODO add your handling code here:
        AgregarArticulos();
    }//GEN-LAST:event_bAgregarArtActionPerformed

    private void tPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPagoKeyReleased
        // SE HACE PARA QUE SE HAGA LA ACCION AL MOMENTO DE LEVANTAR LA TECLA PARA CAPTURAR NUMEROS Y HAGA EL CALCULO DEL CAMBIO
        calculodevuelto();
    }//GEN-LAST:event_tPagoKeyReleased

    private void tTotalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tTotalPropertyChange
        // TODO add your handling code here:
        calculodevuelto();
    }//GEN-LAST:event_tTotalPropertyChange

    private void bRVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRVentaActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            //GUARDAR FACTURA
            cFactura f = new cFactura();
            f.setCliente(ClienteSel);
            f.setEmpleado(EmpleadoSel);
            f.setVentas(ArregloVA);
            f.setCorrelativo(lCorrelativo.getText());
            f.setTotal(tTotal.getText());
            f.setTotalIva(tIVA.getText());
            String formatoF = "dd/MM/yyyy";
            SimpleDateFormat formadate = new SimpleDateFormat(formatoF);
            f.setFecha(formadate.format(new Date()));
            f.setEstado("Efectuada");
            f.setCaja(cbCajas.getSelectedItem().toString());
            f.setCambio(lCCambio.getText());
            f.setPago(tPago.getText());

            ArregloFac.add(f);
            crearbinario();
            actualizarinv();
            Main.resetpanel();
            JOptionPane.showMessageDialog(null, "Venta realizada correctamente :D", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Venta no realizada correctamente (", "MENSAJE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bRVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JButton bAgregarArt;
    private javax.swing.JButton bAgregarCl;
    private javax.swing.JButton bRVenta;
    private javax.swing.JComboBox<String> cbCArticulos;
    private javax.swing.JComboBox<String> cbCajas;
    private javax.swing.JComboBox<String> cbCantArticulos;
    private static javax.swing.JComboBox<String> cbClientes;
    private javax.swing.JComboBox<String> cbEmpleados;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lCCambio;
    private javax.swing.JLabel lCambio;
    private javax.swing.JList<String> lCantidadA;
    private javax.swing.JList<String> lCodigoA;
    private javax.swing.JLabel lCorrelativo;
    private javax.swing.JList<String> lDescripcionA;
    private javax.swing.JList<String> lNombre;
    private javax.swing.JList<String> lPrecioUnitA;
    private javax.swing.JList<String> lSubtotalA;
    private javax.swing.JTextField tIVA;
    private javax.swing.JTextField tPago;
    private javax.swing.JTextField tPuestoE;
    private javax.swing.JTextField tTotal;
    // End of variables declaration//GEN-END:variables
    private void addpanel(JPanel p) {
        p.setLocation(0, 0);
        p.setSize(PanelClientes.getWidth(), 170);
        PanelClientes.removeAll();
        PanelClientes.add(p, BorderLayout.CENTER);
        PanelClientes.revalidate();
        PanelClientes.repaint();
    }

    public static void setearCB() {
        Iterator<cCliente> ITH = pClientes.getArregloC().iterator();
        cbClientes.removeAllItems();
        cbClientes.addItem("Seleccione Cliente");
        while (ITH.hasNext()) {
            cCliente gCliente = ITH.next();
            cbClientes.addItem(gCliente.getNitCliente() + "-" + gCliente.getNombreCliente());
        }
    }

    private void setearCBE() {
        Iterator<cEmpleado> ITH = pEmpleados.getArregloE().iterator();
        cbEmpleados.addItem("Seleccione Empleado");
        while (ITH.hasNext()) {
            cEmpleado gEmpleado = ITH.next();
            cbEmpleados.addItem(gEmpleado.getNombreEmpleado());
        }
    }

    private void setearCBCA() { //COMBO BOX CODIGO DE ARTICULOS
        Iterator<cArticulo> ITH = pArticulos.getArregloA().iterator();
        cbCArticulos.addItem("Seleccione Codigo De Articulo");
        while (ITH.hasNext()) {
            cArticulo gCodArticulo = ITH.next();
            cbCArticulos.addItem(gCodArticulo.getCodigoArticulo());
        }
    }

    private void setearCantBCA(String CodigoArt) { //COMBO BOX CANTIDAD DE ARTICULOS
        Iterator<cArticulo> ITH = pArticulos.getArregloA().iterator();
        cbCantArticulos.removeAllItems();
        cbCantArticulos.addItem("Seleccione Cantidad De Articulo");
        while (ITH.hasNext()) {
            cArticulo gCodArticulo = ITH.next();
            if (gCodArticulo.getCodigoArticulo().equals(CodigoArt)) {
                for (Integer i = 1; i <= Integer.parseInt(gCodArticulo.getCantidad()); i++) {
                    cbCantArticulos.addItem(i.toString());
                }
            }

        }
    }

    private boolean BuscarCliente(String Cliente) {
        boolean flag = false;
        ClienteSel = null;
        Iterator<cCliente> ITH = pClientes.getArregloC().iterator();
        while (ITH.hasNext()) {
            cCliente gCliente = ITH.next();
            String fBusqueda = gCliente.getNitCliente() + "-" + gCliente.getNombreCliente();
            if (fBusqueda.equals(Cliente)) {
                ClienteSel = gCliente;
                flag = true;
            }
        }
        return flag;
    }

    private boolean BuscarEmpleado(String Empleado) {
        boolean flag = false;
        EmpleadoSel = null;
        Iterator<cEmpleado> ITH = pEmpleados.getArregloE().iterator();
        while (ITH.hasNext()) {
            cEmpleado gEmpleado = ITH.next();
            String fBusqueda = gEmpleado.getNombreEmpleado();
            if (fBusqueda.equals(Empleado)) {
                EmpleadoSel = gEmpleado;
                flag = true;
            }
        }
        return flag;
    }

    private cArticulo BuscarArticulo(String Articulo) {
        cArticulo variable = null;
        Iterator<cArticulo> ITH = pArticulos.getArregloA().iterator();
        while (ITH.hasNext()) {
            cArticulo gArticulo = ITH.next();
            String fBusqueda = gArticulo.getCodigoArticulo();
            if (fBusqueda.equals(Articulo)) {
                variable = gArticulo;
            }
        }
        return variable;
    }

    private void AgregarArticulos() {
        cArticulo InsertarArt = BuscarArticulo(cbCArticulos.getSelectedItem().toString());
        if (!validarinv()) {
            if (InsertarArt != null) {
                AgregarLista(InsertarArt);
                settearLista();
            } else {
                JOptionPane.showMessageDialog(null, "ALGO SALIO MAL :(", "MENSAJE", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cantidad de artículo insuficiente", "MENSAJE", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void AgregarLista(cArticulo Artic) {
        Iterator<cVentaArticulo> ITH = ArregloVA.iterator();
        Integer INDEX = null;
        if (!ArregloVA.isEmpty()) {
            while (ITH.hasNext()) {
                cVentaArticulo gVentaArticulo = ITH.next();
                if (gVentaArticulo.getCodigoArticulo().equals(Artic.getCodigoArticulo())) {
                    INDEX = ArregloVA.indexOf(gVentaArticulo); //EL INDEX ES LA POSICION DEL OBJETO QUE SE VA A ACTUALIZAR
                }
            }
            if (INDEX != null) {
                for (cVentaArticulo contA : ArregloVA) {//FORMA DIFERENTE DE NO USAR UN ITERADOR
                    if (INDEX == ArregloVA.indexOf(contA)) {
                        contA.setCantidad(contA.getCantidad() + Integer.parseInt(cbCantArticulos.getSelectedItem().toString()));
                    }
                }
            } else {
                cVentaArticulo vArt = new cVentaArticulo();
                vArt.setCodigoArticulo(Artic.getCodigoArticulo());
                vArt.setDescripcionA(Artic.getDescripcionA());
                vArt.setPrecioUnit(Float.parseFloat(Artic.getPrecioUnit()));
                vArt.setCantidad(Integer.parseInt(cbCantArticulos.getSelectedItem().toString()));
                vArt.setNombreArticulo(Artic.getNombreArticulo());
                ArregloVA.add(vArt);
            }
        } else {
            cVentaArticulo vArt = new cVentaArticulo();
            vArt.setCodigoArticulo(Artic.getCodigoArticulo());
            vArt.setDescripcionA(Artic.getDescripcionA());
            vArt.setPrecioUnit(Float.parseFloat(Artic.getPrecioUnit()));
            vArt.setCantidad(Integer.parseInt(cbCantArticulos.getSelectedItem().toString()));
            vArt.setNombreArticulo(Artic.getNombreArticulo());
            ArregloVA.add(vArt);
        }
    }

    private void settearLista() {
        DefaultListModel<String> ModeloLista1 = new DefaultListModel<>();
        DefaultListModel<String> ModeloLista2 = new DefaultListModel<>();
        DefaultListModel<String> ModeloLista3 = new DefaultListModel<>();
        DefaultListModel<String> ModeloLista4 = new DefaultListModel<>();
        DefaultListModel<String> ModeloLista5 = new DefaultListModel<>();
        DefaultListModel<String> ModeloLista6 = new DefaultListModel<>();
        Float Total = 0f;
        for (cVentaArticulo contA : ArregloVA) {//FORMA DIFERENTE DE NO USAR UN ITERADOR
            Float SubTotal = 1f;//No se puede inicializar un float con un valor
            ModeloLista1.addElement(contA.getCodigoArticulo());
            ModeloLista2.addElement(contA.getDescripcionA());
            ModeloLista3.addElement(contA.getPrecioUnit().toString());
            ModeloLista4.addElement(contA.getCantidad().toString());
            ModeloLista6.addElement(contA.getNombreArticulo());
            SubTotal = contA.getPrecioUnit() * contA.getCantidad();
            ModeloLista5.addElement(SubTotal.toString());
            Total = Total + SubTotal;
        }
        lCodigoA.setModel(ModeloLista1);
        lDescripcionA.setModel(ModeloLista2);
        lPrecioUnitA.setModel(ModeloLista3);
        lCantidadA.setModel(ModeloLista4);
        lSubtotalA.setModel(ModeloLista5);
        lNombre.setModel(ModeloLista6);
        tTotal.setText(Total.toString());
    }

    private void calculodevuelto() {
        Double cambio = 0D;
        Double total = 0D;
        Double iva = 0D;
        try {
            //NAN ES Not a Number tipo flag

            total = Double.parseDouble(tTotal.getText());
            cambio = Double.parseDouble(tPago.getText()) - total;
            lCCambio.setText(cambio.toString());
            iva = total * 0.12;
            tIVA.setText(iva.toString());

        } catch (Exception error) {
            System.out.println(error.getMessage());
            lCCambio.setText("00.00");
        }
    }

    private boolean validar() {
        boolean flag = false;
        if (!"".equals(tTotal.getText())) { //IF INVERSO SI AQUI LA FLAG ES TRUE INGRESA SINO NO
            flag = true;

        } else {
            JOptionPane.showMessageDialog(null, "No has agregado ningun producto :(", "MENSAJE", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!"".equals(tPago.getText())) {
            flag = true;

        } else {
            JOptionPane.showMessageDialog(null, "No se ha realizado ningun tipo de pago :(", "MENSAJE", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!lCCambio.getText().equals("00.00")) {
            flag = true;
            if (Double.parseDouble(lCCambio.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "Error no ha pagado lo suficiente :((", "MENSAJE", JOptionPane.ERROR_MESSAGE);
                return false;

            } else {
                flag = true;

            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha ingresado bien el metodo de pago :(", "MENSAJE", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!(EmpleadoSel == null)) {
            flag = true;
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado el empleado a cargo de la caja:(", "MENSAJE", JOptionPane.ERROR_MESSAGE);
            return false;

        }
        if (!(ClienteSel == null)) {
            flag = true;
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado el cliente:(", "MENSAJE", JOptionPane.ERROR_MESSAGE);
            return false;

        }

        return flag;
    }

    private void correlativo() {

        if (ArregloFac.size() > 0) {
            for (cFactura v : ArregloFac) {
                if (ArregloFac.indexOf(v) == ArregloFac.size() - 1) {
                    Integer correlativo = 1 + Integer.parseInt(v.getCorrelativo());
                    lCorrelativo.setText(correlativo.toString());
                }
            }
        } else {
            lCorrelativo.setText("1");
        }
    }

    public static void leerbinario() {
        FileInputStream fis = null;
        ObjectInputStream ois = null;

        try {

            fis = new FileInputStream("bFacturas.dat");
            ois = new ObjectInputStream(fis);
            ArregloFac = (ArrayList<cFactura>) ois.readObject(); //es necesario el casting

        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        } catch (IOException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (fis != null) {
                    fis.close();
                }
                if (ois != null) {
                    ois.close();
                }
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
        }
    }

    private void crearbinario() {
        FileOutputStream fos = null;
        ObjectOutputStream ous = null;

        try {
            //Se crea el fichero
            fos = new FileOutputStream("bFacturas.dat");
            ous = new ObjectOutputStream(fos);

            //Se escribe el objeto en el fichero
            ous.writeObject(ArregloFac);

        } catch (FileNotFoundException e) {
            System.out.println("1" + e.getMessage());
        } catch (IOException e) {
            System.out.println("2" + e.getMessage());
        } finally {
            try {
                if (fos != null) {
                    fos.close();
                }
                if (ous != null) {
                    ous.close();
                }
            } catch (IOException e) {
                System.out.println("3" + e.getMessage());
            }
        }
    }

    private void actualizarinv() {

        for (cVentaArticulo act : ArregloVA) {
            for (cArticulo art : pArticulos.getArregloA()) {
                System.out.println(art.getCodigoArticulo());
                System.out.println(act.getCodigoArticulo());
                if (act.getCodigoArticulo().equals(art.getCodigoArticulo())) {
                    Integer newcant = Integer.parseInt(art.getCantidad()) - act.getCantidad();
                    art.setCantidad(newcant.toString());
                    pArticulos.crearBinarioAr();
                    System.out.println(newcant);
                }
            }
        }
    }

    private boolean validarinv() {
        boolean flag = false;
        for (cVentaArticulo act : ArregloVA) {
            if (act.getCodigoArticulo().equals(cbCArticulos.getSelectedItem().toString())) {
                for (cArticulo art : pArticulos.getArregloA()) {
                    if (act.getCodigoArticulo().equals(art.getCodigoArticulo())) {
                        Integer newcant = Integer.parseInt(art.getCantidad()) - (act.getCantidad()+Integer.parseInt(cbCantArticulos.getSelectedItem().toString()));
                        if (newcant < 0) {
                            return true;
                        }
                    }
                }
            }
        }
        return flag;
    }
}
