/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import Clases.cArticulos;
import Clases.cProveedores;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Chefu
 */
public class pProveedores extends javax.swing.JPanel {

    /**
     * Creates new form pProveedor
     */
    cProveedores ProveedorEncontrado = null;
    ArrayList<cProveedores> ArregloP = new ArrayList<cProveedores>();

    public pProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lProveedores = new javax.swing.JLabel();
        eCodigoP = new javax.swing.JLabel();
        eNitP = new javax.swing.JLabel();
        eNombreP = new javax.swing.JLabel();
        eDireccionP = new javax.swing.JLabel();
        eCelularP = new javax.swing.JLabel();
        tCodigoP = new javax.swing.JTextField();
        tNitP = new javax.swing.JTextField();
        tNombreP = new javax.swing.JTextField();
        tDireccionP = new javax.swing.JTextField();
        tCelularP = new javax.swing.JTextField();
        bAgregarP = new javax.swing.JButton();
        bEliminarP = new javax.swing.JButton();
        bBuscarP = new javax.swing.JButton();
        bModificarP = new javax.swing.JButton();
        bReporteP = new javax.swing.JButton();
        bBinarioP = new javax.swing.JButton();

        lProveedores.setText("Proveedores");

        eCodigoP.setText("Codigo de Proveedor:");

        eNitP.setText("Nit de Proveedor:");

        eNombreP.setText("Nombre de Proveedor:");

        eDireccionP.setText("Direccion de Proveedor:");

        eCelularP.setText("Celular de Proveedor:");

        bAgregarP.setText("Agregar");
        bAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarPActionPerformed(evt);
            }
        });

        bEliminarP.setText("Eliminar");
        bEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarPActionPerformed(evt);
            }
        });

        bBuscarP.setText("Buscar");
        bBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarPActionPerformed(evt);
            }
        });

        bModificarP.setText("Modificar");
        bModificarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarPActionPerformed(evt);
            }
        });

        bReporteP.setText("Reporte");
        bReporteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReportePActionPerformed(evt);
            }
        });

        bBinarioP.setText("Binario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lProveedores)
                .addGap(257, 257, 257))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eCodigoP)
                    .addComponent(eNitP)
                    .addComponent(eNombreP)
                    .addComponent(eDireccionP)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(eCelularP)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bAgregarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bModificarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tCelularP)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tCodigoP)
                                    .addComponent(tNitP)
                                    .addComponent(tNombreP, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                                    .addComponent(tDireccionP))))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bReporteP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bBinarioP))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bEliminarP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addComponent(bBuscarP)))
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lProveedores)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCodigoP)
                    .addComponent(tCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNitP)
                    .addComponent(tNitP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNombreP)
                    .addComponent(tNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eDireccionP)
                    .addComponent(tDireccionP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCelularP)
                    .addComponent(tCelularP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregarP)
                    .addComponent(bEliminarP)
                    .addComponent(bBuscarP))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bModificarP)
                    .addComponent(bReporteP)
                    .addComponent(bBinarioP))
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarPActionPerformed
        // TODO add your handling code here:        
        cProveedores oProveedores = new cProveedores();
        oProveedores.setCodigoProveedorP(tCodigoP.getText());
        oProveedores.setNitProveedor(tNitP.getText());
        oProveedores.setNombreProveedor(tNombreP.getText());
        oProveedores.setDireccionProveedor(tDireccionP.getText());
        oProveedores.setCelularProveedor(tCelularP.getText());

        ArregloP.add(oProveedores);

        setteo();

    }//GEN-LAST:event_bAgregarPActionPerformed

    private void bEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarPActionPerformed
        // TODO add your handling code here:

        if (eliminarP(ProveedorEncontrado) && ProveedorEncontrado != null) {
            JOptionPane.showMessageDialog(null, "Proveedor Eliminado Correctamente", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            setteo();
        } else {
            JOptionPane.showMessageDialog(null, "Proveedor No Eliminado", "MENSAJE", JOptionPane.ERROR_MESSAGE);
            setteo();
        }


    }//GEN-LAST:event_bEliminarPActionPerformed

    private void bBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarPActionPerformed
        // TODO add your handling code here:
        ProveedorEncontrado = buscarP(tCodigoP.getText());
        if (ProveedorEncontrado != null) {
            tCodigoP.setText(ProveedorEncontrado.getCodigoProveedorP());
            tNitP.setText(ProveedorEncontrado.getNitProveedor());
            tNombreP.setText(ProveedorEncontrado.getNombreProveedor());
            tDireccionP.setText(ProveedorEncontrado.getDireccionProveedor());
            tCelularP.setText(ProveedorEncontrado.getCelularProveedor());
        } else {
            setteo();
            JOptionPane.showMessageDialog(null, "Proveedor no encontrado", "MENSAJE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bBuscarPActionPerformed

    private void bModificarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarPActionPerformed
        // TODO add your handling code here:
        if (modificarP(ProveedorEncontrado) && ProveedorEncontrado != null) {

            JOptionPane.showMessageDialog(null, "Proveedor Modificado Correctamente", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            setteo();
        } else {
            JOptionPane.showMessageDialog(null, "Proveedor No Modificado", "MENSAJE", JOptionPane.ERROR_MESSAGE);
            setteo();
        }
    }//GEN-LAST:event_bModificarPActionPerformed

    private void bReportePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReportePActionPerformed
        // TODO add your handling code here:
        html();
    }//GEN-LAST:event_bReportePActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarP;
    private javax.swing.JButton bBinarioP;
    private javax.swing.JButton bBuscarP;
    private javax.swing.JButton bEliminarP;
    private javax.swing.JButton bModificarP;
    private javax.swing.JButton bReporteP;
    private javax.swing.JLabel eCelularP;
    private javax.swing.JLabel eCodigoP;
    private javax.swing.JLabel eDireccionP;
    private javax.swing.JLabel eNitP;
    private javax.swing.JLabel eNombreP;
    private javax.swing.JLabel lProveedores;
    private javax.swing.JTextField tCelularP;
    private javax.swing.JTextField tCodigoP;
    private javax.swing.JTextField tDireccionP;
    private javax.swing.JTextField tNitP;
    private javax.swing.JTextField tNombreP;
    // End of variables declaration//GEN-END:variables

    private cProveedores buscarP(String CodigoP) {
        Iterator<cProveedores> ITP = ArregloP.iterator();
        cProveedores p = null;
        while (ITP.hasNext()) {
            cProveedores P = ITP.next();
            if (P.getCodigoProveedorP().equals(CodigoP)) {
                p = P;
            }
        }
        return p;
    }

    private void setteo() {
        tCodigoP.setText("");
        tNitP.setText("");
        tNombreP.setText("");
        tDireccionP.setText("");
        tCelularP.setText("");
        tCodigoP.requestFocus(); //Solicita la colocacion del cursor en el campo de texto Nit
    }

    private boolean eliminarP(cProveedores e) {
        boolean flag = false;
        try {
            Iterator<cProveedores> ITP = ArregloP.iterator();
            while (ITP.hasNext()) {
                cProveedores P = ITP.next();
                if (P.getCodigoProveedorP().equals(e.getCodigoProveedorP())) {
                    ITP.remove();
                    flag = true;
                }
            }
        } catch (Exception error) {
            flag = false;
            System.out.println("El Erro fue:" + error.getMessage());
        }

        return flag; //Flag es igual a true solo si lo removio dentro del void
    }

    private boolean modificarP(cProveedores m) {
        boolean flag = false;
        try {
            Iterator<cProveedores> ITP = ArregloP.iterator();
            while (ITP.hasNext()) {
                cProveedores P = ITP.next();
                if (P.getNitProveedor().equals(m.getNitProveedor())) {
                    flag = true;
                    P.setCodigoProveedorP(tCodigoP.getText());
                    P.setNitProveedor(tNitP.getText());
                    P.setNombreProveedor(tNombreP.getText());
                    P.setDireccionProveedor(tDireccionP.getText());
                    P.setCelularProveedor(tCelularP.getText());
                }
            }
        } catch (Exception error) {
            flag = false;
            System.out.println("El Error fue:" + error.getMessage());
        }

        return flag; //Flag es igual a true solo si lo removio dentro del void
    }

    private void html() {

        BufferedWriter ficheroSalida;
        try {
            String rows = "";
            Iterator<cProveedores> ITP = ArregloP.iterator();

            ficheroSalida = new BufferedWriter(new FileWriter(new File("ReporteP.html")));
            while (ITP.hasNext()) {
                cProveedores P = ITP.next();
                rows = rows + "            <tr>\n"
                        + "                <td>" + P.getCodigoProveedorP() + "</td>\n"
                        + "                <td>" + P.getNitProveedor() + "</td>\n"
                        + "                <td>" + P.getNombreProveedor() + "</td>\n"
                        + "                <td>" + P.getDireccionProveedor() + "</td>\n"
                        + "                <td>" + P.getCelularProveedor() + "</td>\n"
                        + "            </tr>";
            }
            ficheroSalida.write("<!DOCTYPE html>\n"
                    + "<html lang=\"en\">\n"
                    + "\n"
                    + "<head>\n"
                    + "    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n"
                    + "        integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\n"
                    + "    <meta charset=\"UTF-8\">\n"
                    + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                    + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                    + "    <title>Reportes</title>\n"
                    + "</head>\n"
                    + "\n"
                    + "<body>\n"
                    + "    <table class=\"w-100 table table-dark table-hover\">\n"
                    + "        <thead>\n"
                    + "            <tr>\n"
                    + "                <th>Codigo</th>\n"
                    + "                <th>Nit</th>\n"
                    + "                <th>Nombre</th>\n"
                    + "                <th>Direccion</th>\n"
                    + "                <th>Celular</th>\n"
                    + "            </tr>\n"
                    + "        </thead>\n"
                    + "        <tbody>\n"
                    + rows
                    + "        </tbody>\n"
                    + "    </table>\n"
                    + "</body>\n"
                    + "\n"
                    + "</html>");
            ficheroSalida.close();
        } catch (IOException error) {
            System.out.println("El Error fue:" + error.getMessage());
        }
    }
}
