/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import Clases.cCliente;

/**
 *
 * @author Chefu
 */
public class pViewClientes extends javax.swing.JPanel {

    /**
     * Creates new form pViewClientes
     */
    public pViewClientes(cCliente ClienteEnc) {
        initComponents();
        tNitCl.setText(ClienteEnc.getNitCliente());
        tNombreCl.setText(ClienteEnc.getNombreCliente());
        tDireccionCl.setText(ClienteEnc.getDireccionCliente());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eDireccionCl = new javax.swing.JLabel();
        tNitCl = new javax.swing.JTextField();
        tDireccionCl = new javax.swing.JTextField();
        tNombreCl = new javax.swing.JTextField();
        eNitCl = new javax.swing.JLabel();
        eNombreCl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        eDireccionCl.setText("Direccion de Cliente:");

        tNitCl.setEditable(false);

        tDireccionCl.setEditable(false);

        tNombreCl.setEditable(false);

        eNitCl.setText("Nit de Cliente:");

        eNombreCl.setText("Nombre de Cliente:");

        jLabel1.setText("Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eDireccionCl)
                            .addComponent(eNombreCl)
                            .addComponent(eNitCl))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tDireccionCl, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNombreCl, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNitCl, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNitCl)
                    .addComponent(tNitCl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNombreCl)
                    .addComponent(tNombreCl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eDireccionCl)
                    .addComponent(tDireccionCl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tDireccionCl, tNitCl, tNombreCl});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eDireccionCl;
    private javax.swing.JLabel eNitCl;
    private javax.swing.JLabel eNombreCl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tDireccionCl;
    private javax.swing.JTextField tNitCl;
    private javax.swing.JTextField tNombreCl;
    // End of variables declaration//GEN-END:variables
}
